name: Assignment Two CI Pipeline
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: "18"
        - name: running script
          working-directory: ./src
          run: bash Deploy.sh